services:
  api:
    container_name: sprint4_entrega
    image: sprint4_entrega_express
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=tiburcio
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB=products_management
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tiburcio
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql
